const Icon = {
  AppLogo: require('../assets/appLogo.png'),
  Splash3: require('../assets/splash3.png'),
  HeartBackground: require('../assets/heartBg.png'),
  Intro: require('../assets/intro.png'),
  Intro2: require('../assets/intro2.png'),
  AppLogo2: require('../assets/appLogo2.png'),
  AppLogoPink: require('../assets/appLogoPink.png'),
  ChatLogoPink: require('../assets/chatPink.png'),
  ShowPassword: require('../assets/showPassword.png'),
  Mail: require('../assets/mail.png'),
  AppleLogo: require('../assets/appleLogo.png'),
  GoogleLogo: require('../assets/googleLogo.png'),
  ErrorLogo: require('../assets/errorLogo.png'),
  BackArrow: require('../assets/backArrow.png'),
  ForgotPassICon: require('../assets/forgotPasswordIcon.png'),
  NewPassLogo: require('../assets/newPassLogo.png'),
  CongratulationBackground: require('../assets/congratulation.png'),
  Search: require('../assets/search.png'),
  HeaderLogo: require('../assets/headerLogo.png'),
  BellIcon: require('../assets/bell.png'),
  TestIcon: require('../assets/test.png'),
  TabIcon: require('../assets/TabIcon/tab.png'),
  Tab2Icon: require('../assets/TabIcon/tab2.png'),
  Tab3Icon: require('../assets/TabIcon/tab3.png'),
  SuccessAccount: require('../assets/successAccount.png'),
  dp1: require('../assets/DP/dp1.png'),
  dp2: require('../assets/DP/dp2.png'),
  dp3: require('../assets/DP/dp3.png'),
  dp4: require('../assets/DP/dp4.png'),
  dp5: require('../assets/DP/dp5.png'),
  dp6: require('../assets/DP/dp6.png'),
  dp7: require('../assets/DP/dp7.png'),
  dp8: require('../assets/DP/dp8.png'),
  Dots: require('../assets/dots.png'),
  Report: require('../assets/report.png'),
  Block: require('../assets/block.png'),

  Banner: require('../assets/Banner/banner.jpg'),
  Banner2: require('../assets/Banner/banner2.jpg'),
  Banner3: require('../assets/Banner/banner3.jpg'),
  Banner4: require('../assets/Banner/banner4.jpg'),
  Banner5: require('../assets/Banner/banner5.jpg'),
  Banner6: require('../assets/Banner/banner6.jpg'),
  Congratulation : require("../assets/Banner/Cong.png"),
};

export default Icon;
