const DummyData = [
  {id: 1, name: 'Gaming'},
  {id: 2, name: 'Dancing'},
  {id: 3, name: 'Animals'},
  {id: 4, name: 'Language'},
  {id: 5, name: 'Movies'},
  {id: 6, name: 'Gym'},
  {id: 7, name: 'Music'},
  {id: 8, name: 'Fashion'},
  {id: 9, name: 'Writting'},
  {id: 10, name: 'People'},
  {id: 11, name: 'Food&Drink'},
  {id: 12, name: 'Travel'},
  {id: 13, name: 'Hockey'},
  {id: 14, name: 'BasketBall'},
  {id: 15, name: 'Slam Poetry'},
  {id: 16, name: 'Home Workout'},
  {id: 17, name: 'Events'},
  {id: 18, name: 'DJ Nights'},
  {id: 19, name: 'Long Drives'},
  {id: 20, name: 'Food'},
  {id: 21, name: 'Beaches'},
  {id: 22, name: 'Music Concerts'},
  {id: 23, name: 'Gaming'},
  {id: 24, name: 'Dancing'},
  {id: 25, name: 'Animals'},
  {id: 26, name: 'Language'},
  {id: 27, name: 'Movies'},
  {id: 28, name: 'Gym'},
  {id: 29, name: 'Music'},
  {id: 30, name: 'Fashion'},
  {id: 31, name: 'Writting'},
  {id: 32, name: 'People'},
  {id: 33, name: 'Food&Drink'},
  {id: 34, name: 'Travel'},
  {id: 35, name: 'Hockey'},
  {id: 36, name: 'BasketBall'},
  {id: 37, name: 'Slam Poetry'},
  {id: 38, name: 'Home Workout'},
  {id: 39, name: 'Events'},
  {id: 40, name: 'DJ Nights'},
  {id: 41, name: 'Long Drives'},
  {id: 42, name: 'Food'},
  {id: 43, name: 'Beaches'},
  {id: 44, name: 'Music Concerts'},
];

export default DummyData;
