const english = {
  email: 'Email',
  name: 'Name',
  fullName: 'Full Name',
  phone: 'Phone Number',
  dob: 'Date of Birth',
  password: 'Password',
  conpassword: 'Confirm Password',
  letSignIn: `Let's Sign You In`,
  enterEmail: 'Please enter email',
  enterPassword: 'Please enter password',
  enterConPassword: 'Please enter confirm password',
  location: 'Location',
  bio: 'Bio',
  save: 'Save',
  letSignIn: `Let's Sign You In`,
  enterEmail: 'Please enter email',
  enterPassword: 'Please enter password',
  enterName: 'Please enter the Name',
  enterPhone: 'Please enter Phone Number',
  enterLocation: 'Please enter Location',
  enterBio: 'Please enter few lines about yourself',
  selectDob: 'Please select you DOB',
  rememberMe: 'Remember me',
  forgetPassword: 'Forget Password?',
  changePassword:'Change Password',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  usingEmail: 'Or Log In Using Email',
  logInGoogle: 'Log In with Google',
  logInApple: 'Log In with Apple',
  enterValidEmail: 'Please enter the Valid Email',
  letSignUp: "Let's Sign Up",
  alreadyAccount: 'Already have an account?',
  selectContact: 'Select which contact should we use to reset your password',
  validPhone: 'Please enter the Valid Phone Number',
  selectCountry: 'Select Country',
  next: 'Next',
  goToHomePage: 'Go to homepage',
  addBestPhotos: 'Add Your Best Photos',
  addPhotoContent: 'Add your photos to get a higher amount of daily matches',
  selectYourInterest: 'Select Your Interest',
  selectText:
    'Select your interests to match with users who have similar things in common',
  great: 'Great',
  accountSuccess: 'Your account has been created successfully',
  editProfile: 'Edit Profile',
  searchCriteria: 'Search Criteria',
  goUpgradeVip: 'Go Upgrade Vip',
  forgetPassword: 'Forget Password',
  logout: 'Logout',
  changeProfile: 'Change Profile',
  verifyCode: 'Verify Code',
  codeSent: 'A code has been sent to ',
  resendCode: 'Resend Code',
  continue: 'Continue',
  newPassword: 'New Password',
  confirmNewPassword: 'Confirm New Password',
  gender: 'Gender',
  selectGender: 'Please select Gender',
  age: 'Age',
  reset: 'Reset',
  applyFilter: 'Apply Filter',
  upgrade: 'Upgrade',
  popular: 'Popular',
  save26: 'Save 26%',
  genderError: 'Please select Gender',
  nope :"NOPE",
  like :"LIKE",
  supperLike :"SUPER LIKE",
  notification :"Notification",
  likeProfile :"This person like your Profile",
  description :"Description",
  back : "Back",
  sendMesg:"Send Message...",
  aboutUs :"About us",
  interest :"Interest",
  congratulations: 'Congratulations!',
  matchFound:"Match Found",
  skip:"SKIP",
  likeClick:"Liked Profile"
};

export default english;
